# Clearly hypothetical other cases; no claims of actual events or official decisions.
STORIES={
0:'Imagine a different driver whose parked car is struck outside a sporting event, with a repair invoice but unresolved details about the insurance claim.',
1:'Imagine a different online argument where one participant posts a provocative invitation to continue the quarrel elsewhere.',
2:'Imagine a different shop owner repeatedly checking a payment dashboard after several days without a successful payout.',
3:'Imagine a different passenger whose flight is cancelled and who writes to the airline asking for money back.',
4:'Imagine a different support record containing both a duplicate order charge and an unrelated password-reset question.',
5:'Imagine a different email promising an employee a surprise bonus in exchange for sending login information.',
6:'Imagine a different weather request whose tool trace resolves a city but still has an unresolved mismatch in forecast arguments.',
7:'Imagine two different CV records sharing a name and a recent employer while leaving personal identity incompletely established.',
8:'Imagine a different cardholder asking how many disposable virtual cards can be created in one day.',
9:'Imagine a different merchant struggling to connect a payment service and worrying about missed sales.',
10:'Imagine a different customer describing duplicate billing, an account-access issue, and a suggestion for another payment method in one note.',
11:'Imagine a different invoice naming a customer and an amount due, with a date and payment terms but no receipt confirming payment.',
12:'Imagine a different buyer looking at a shipment marked label created and wondering whether the purchase was charged.',
13:'Imagine a different bottle with a straw lid and a description of the bicycle cages it fits.',
14:'Imagine a different code change mixing a bug fix, a refactor, and a dependency update in its description.',
15:'Imagine a different buyer whose shoes arrive late in the wrong size and who also notices two card charges.',
16:'Imagine a different buyer returning an item and asking when the refund will appear.',
17:'Imagine a different customer repeatedly contacting support and eventually requesting a human representative.',
18:'Imagine a different browser defect that occurs in one browser while another browser still works.',
19:'Imagine a different export problem where PDF never finishes and different colleagues report different experiences with CSV.',
20:'Imagine a different store unable to process orders while an integration returns server errors.',
21:'Imagine a different support note reporting duplicate billing and requesting a quick fix.',
22:'Imagine a different migration document that mixes headings, ordered setup steps, and conversational asides.',
23:'Imagine a different tasting note mixing ripe fruit descriptions with structural details and a restrained caveat.',
24:'Imagine a different reader who sees instructions about processing a token expiration field and assumes that every token must contain that field.',
25:'Imagine a different company filing that distinguishes proposed research activity from money already spent.',
26:'Imagine a different documentation passage about login sessions being used to answer a question about refresh-token expiry.',
27:'Imagine a different message proposing a design review next Thursday without giving a calendar date.',
28:'Imagine a different contract stating its effective date and its expiry date in separate clauses.',
29:'Imagine a different request to return a signed form by a named month and day without giving the year.',
30:'Imagine a different message saying that a survey closes today at a particular time.',
31:'Imagine two different beer listings that share a brewery and alcohol percentage but have partly different names.',
32:'Imagine a different trading request naming two securities and asking for a comparison over the past month.',
33:'Imagine a different role-play message claiming the assistant can bypass its normal constraints and then asking a factual question.',
34:'Imagine a different reader reducing a detailed privacy regulation to a broad personal impression about consent and individual rights.',
35:'Imagine a different email whose sender asks for a receipt at a personal address instead of the departmental mailbox.',
36:'Imagine a different contact notice listing a main desk, a fax, and a mobile number while mentioning which one to call urgently.',
37:'Imagine a different invoice showing a subtotal, tax, and total, with a credit already reflected in the amount.',
38:'Imagine a different legal-research comparison involving two organizations and a question about government action.',
39:'Imagine a different university webpage with a program title, navigation links, and structured extraction fields.',
40:'Imagine a different service agreement defining account terms and discussing ownership of user-uploaded content in another section.',
41:'Imagine a different analyst requesting a presentation outline with branding and links back to spreadsheet cells.',
42:'Imagine a different engineer’s resume mixing frontend work, project outcomes, mentoring, and some less detailed backend claims.',
43:'Imagine a different frozen dessert with ice cream between two wafers, whose name makes someone think immediately of a sandwich.',
44:'Imagine a different list mixing apple and orange with place names, function words, and technical vocabulary.',
45:'Imagine a different buyer unhappy with how clothing fits who asks about options without naming a preferred remedy.',
46:'Imagine a different apparent payroll email asking the recipient to send a login password to obtain a bonus.',
47:'Imagine a different buyer asking to swap delivered shoes for another size.',
48:'Imagine a different export bug with mixed CSV reports and no complete browser-version or reproduction details.',
49:'Imagine a different short support message saying the customer was charged twice and needs help.',
50:'Imagine a different short billing complaint that adds an explicit request for immediate help.',
51:'Imagine a different message reporting two charges but not explicitly asking for a particular remedy.',
52:'Imagine a different customer asking someone to investigate two charges for one order without explicitly requesting a refund.',
}
TRADING=[
'Imagine a different terse market request naming a stock and an interval but leaving the output format unstated.',
'Imagine a different trader asking at what time of day a security trades most actively.',
'Imagine a different market question asking what moved today without naming individual securities.',
'Imagine a different user asking which ticker symbols a trading tool supports.',
'Imagine a different request asking how the market performed during the week.',
'Imagine a different request explicitly asking for candlesticks with a moving-average overlay.',
'Imagine a different request comparing three named securities over several months.',
'Imagine a different trader asking about the volatility of one security.',
'Imagine a different request asking for the day’s largest market losers.',
'Imagine a different request for a security’s worst quarterly drawdown with an explicit chart request.',
'Imagine a different request asking for statistics on a market ETF over the last month.',
'Imagine a different request naming a stock, a daily interval, and volume.',
'Imagine a different trader asking whether one semiconductor stock has recently tracked another.',
]
STORIES.update({53+i:v for i,v in enumerate(TRADING)})
