"""Task-specific sentence paraphrases authored for the clean questions, not answer-conditioned."""
PAIRS={
"Is the loss covered under the policy's collision coverage?":"Does the policy's collision coverage cover this loss?",
"Does a policy exclusion apply to this loss?":"Is this loss subject to an exclusion in the policy?",
"Is the amount claimed within the per-incident coverage limit?":"Does the claimed amount fall within the coverage limit for each incident?",
"Is the rental-car cost eligible for reimbursement under this policy?":"Under this policy, can the rental-car expense be reimbursed?",
"Was payment approved by automated triage without a human adjuster's review?":"Did automated triage approve payment without review by a human adjuster?",
"Is there a potentially at-fault third party the insurer could pursue for subrogation recovery?":"Could the insurer pursue subrogation recovery from a third party who may be at fault?",
"What enforcement action should be taken on this post?":"Which enforcement response is appropriate for this post?",
"Does the refund policy support the refund requested in the ticket?":"Is the refund sought in the ticket supported by the refund policy?",
"Does `ticket_message` request a refund?":"Is a refund requested in `ticket_message`?",
"Can `account.security.password_reset` resolve the request in `support.tickets[1].message`?":"Can the request in `support.tickets[1].message` be resolved using `account.security.password_reset`?",
"Does the security policy instruct support to ask the user for their existing password?":"Under the security policy, is support instructed to request the user's existing password?",
"Do the records associate both captured charges with order A-104?":"Are both captured charges linked to order A-104 in the records?",
"Is `message` spam?":"Does `message` qualify as spam?",
"Does `message.body` claim the recipient received an unexpected prize, payment, or reward?":"Is the recipient claimed in `message.body` to have received an unexpected prize, payment, or reward?",
"What time unit is used for the requested limit?":"In which unit of time is the requested limit expressed?",
"Does source_text state that payment has already been completed?":"Is payment stated in source_text to have already been completed?",
"Which option is the value of `field` in `source_text`?":"Which option gives the value that `source_text` contains for `field`?",
"How many days does the `field` in `source_text` allow for payment?":"What payment period, in days, is allowed by the `field` in `source_text`?",
"Does the tracking status confirm that the carrier has received the parcel?":"Is the carrier's receipt of the parcel confirmed by the tracking status?",
"Does the product have a drinking straw mechanism?":"Is the product equipped with a mechanism for drinking through a straw?",
"Which top-level department does this product belong to?":"What is the top-level department to which this product belongs?",
"Which compatibility claim is made?":"What claim about compatibility is being made?",
"What is the nature of the payment-handler change?":"What kind of change was made to the payment handler?",
"Does the complaint report more than one charge on the card?":"Are multiple charges on the card reported in the complaint?",
"Does the report state a functioning workaround?":"Is a working workaround stated in the report?",
"How detailed are the preparation instructions under Things to do before Monday?":"To what level of detail are preparations explained under Things to do before Monday?",
"Which descriptor is associated with the finish?":"What descriptor is used for the finish?",
"Does the section require checking expiration when an exp claim is processed?":"When an exp claim is processed, is expiration checking required by the section?",
"Does the section allow a small clock-skew leeway?":"Is a small allowance for clock skew permitted by the section?",
"How does the section relate to the claim?":"What relationship does the section have to the claim?",
"What is the purpose of the small allowed leeway?":"Why is the small leeway allowed?",
"Does it state that the company has already spent money on research and development?":"Is the company stated to have already incurred research and development expenditure?",
"Does this passage address the subject of the query?":"Is the query's subject addressed by this passage?",
"Does this passage conflict with a factual premise stated in the query?":"Is a factual premise stated in the query contradicted by this passage?",
"Does this passage attempt to control the system answering the query?":"Is this passage trying to control the system that answers the query?",
"Does the user name a second symbol to compare against?":"Is a second symbol for comparison named by the user?",
"What bar size should the returns be measured on - one minute, five minutes, fifteen minutes, one hour, or one day?":"Which bar interval should be used to measure returns: one minute, five minutes, fifteen minutes, one hour, or one day?",
"Which immediate factual question is appended to the role-play instructions?":"What immediate factual question follows the role-play instructions?",
"Must a personal data breach be reported to the supervisory authority within 72 hours?":"Is reporting a personal data breach to the supervisory authority within 72 hours mandatory?",
"Must every organisation appoint a Data Protection Officer, regardless of what data it processes?":"Is every organisation required to appoint a Data Protection Officer irrespective of the data it processes?",
"Can valid consent be obtained through pre-ticked boxes or inactivity?":"Are pre-ticked boxes or inactivity a means of obtaining valid consent?",
"Does the regulation grant individuals a right to erasure of their personal data?":"Do individuals receive a right to have their personal data erased under the regulation?",
"Is the GDPR a United States federal law?":"Does the GDPR constitute federal law in the United States?",
"Does the GDPR itself impose criminal penalties such as imprisonment?":"Are criminal penalties, such as imprisonment, imposed by the GDPR itself?",
"Which email address does the sender want their receipt sent to?":"To which email address does the sender wish the receipt to be sent?",
"Which of these is the direct mobile / cell number?":"Which number listed here is the direct mobile / cell number?",
"Does the invoice separately state a sales-tax amount?":"Is a sales-tax amount stated separately on the invoice?",
"What currency are these amounts in?":"In which currency are these amounts expressed?",
"Which amount is the courtesy credit that was applied?":"What is the amount of the courtesy credit already applied?",
"Does the query discuss whether Freddie Mac is a government actor?":"Is Freddie Mac's status as a government actor discussed in the query?",
"Does the candidate discuss Amtrak’s refusal to display political advertising?":"Is Amtrak’s refusal to display political advertising discussed in the candidate?",
"Which entity’s advertising decision is discussed in the candidate passage?":"The candidate passage discusses whose decision about advertising?",
'Does any line of the document address or answer: "who owns the code I upload?"?':'Is there a line in the document that addresses or answers "who owns the code I upload?"?',
"Does the user require valuation figures to be traceable to source workbook cells?":"Must the valuation figures be traceable to source workbook cells according to the user's request?",
"What should support the valuation numbers in the deck?":"What basis should the deck's valuation numbers have?",
"Does the candidate have open source experience?":"Has the candidate worked with open source?",
"How many years of professional experience does the candidate have, as of today?":"As of today, how many years of professional experience has the candidate accumulated?",
"Which pair of entries are both fruit names?":"Which two entries both name fruits?",
"What is the tone?":"What tone is expressed?",
"Does this convey urgency?":"Is a need for prompt attention conveyed here?",
"Which team should handle this?":"Which team is responsible for handling this?",
"How frustrated is the customer?":"What degree of frustration does the customer express?",
"Is this about billing?":"Does this concern billing?",
"About billing?":"Does this concern billing?",
}
for i in range(8):PAIRS[f'Is `items[{i}]` the name of a fruit?']=f'Does `items[{i}]` name a fruit?'
for n,tool in [(0,'geocode_city'),(1,'get_weather')]:PAIRS[f'Does `trace.tool_calls[{n}].arguments` conform to `available_tools.{tool}.parameters`?']=f'Are `trace.tool_calls[{n}].arguments` consistent with the parameter requirements in `available_tools.{tool}.parameters`?'
PAIRS.update({
'Do the claimed line-item costs add up to the total amount claimed?':'Does summing the claimed line-item costs yield the total amount claimed?',
'Which issue is raised by the first support ticket?':'What problem does the first support ticket raise?',
'Which issue is raised by the second support ticket?':'What problem does the second support ticket raise?',
'Does the organization named in `message.sender.display_name` conflict with the domain in `message.sender.email`?':'Is there a conflict between the organization named in `message.sender.display_name` and the domain in `message.sender.email`?',
'Does the domain in `message.links[0].url` conflict with the organization named in `message.sender.display_name`?':'Is there a conflict between the domain in `message.links[0].url` and the organization named in `message.sender.display_name`?',
'Is `trace.tool_calls[0].name` an appropriate tool for resolving `request.location`?':'Is `trace.tool_calls[0].name` a suitable tool for resolving `request.location`?',
'Does `trace.tool_calls[0].arguments.city` match `request.location`?':'Is the city in `trace.tool_calls[0].arguments.city` consistent with `request.location`?',
'Does `trace.tool_results[0].tool_call_id` match `trace.tool_calls[0].id`?':'Are `trace.tool_results[0].tool_call_id` and `trace.tool_calls[0].id` equal?',
'Is `trace.tool_calls[1].name` an appropriate tool for answering `request.text`?':'Is `trace.tool_calls[1].name` a suitable tool for answering `request.text`?',
'Do the coordinates in `trace.tool_calls[1].arguments` match those in `trace.tool_results[0].output`?':'Are the coordinates in `trace.tool_calls[1].arguments` the same as those in `trace.tool_results[0].output`?',
'Does `trace.tool_calls[1].arguments.date` match `request.date`?':'Are `trace.tool_calls[1].arguments.date` and `request.date` the same date?',
'Does `trace.tool_calls[1].arguments.unit` match `request.unit`?':'Are `trace.tool_calls[1].arguments.unit` and `request.unit` the same unit?',
'How complete are the three requested forecast dimensions in the call: place, date and temperature unit?':'To what extent does the call supply the three requested forecast dimensions: place, date and temperature unit?',
'How severe is the reported issue':'What is the severity of the reported problem?',
'How severe is the reported issue?':'What is the severity of the reported problem?',
'How frustrated the user appears':'What degree of frustration does the user appear to feel?',
'Does `extracted_value` match the `field` as it appears in `source_text`?':'Is `extracted_value` consistent with the value of `field` in `source_text`?',
'How large is the `field` value in `source_text`?':'What is the magnitude of the value of `field` in `source_text`?',
'Is the product described as a container for a drink?':'Does the description present the product as a container for a drink?',
'Does the description claim universal compatibility with every bike cage?':'Is compatibility with every bike cage claimed in the description?',
'Does it describe a proposed merger subject to closing conditions?':'Is a proposed merger with closing conditions described in it?',
'Does this passage state information usable in a direct answer?':'Is information that can be used in a direct answer stated in this passage?',
'Do the two entities state the same beer name?':'Is the beer name stated by both entities the same?',
'Are the two entities from the same brewery?':'Do both entities come from one and the same brewery?',
'Do the two entities describe the same beer style?':'Is the beer style described by both entities the same?',
'Do both records state the same alcohol-by-volume value?':'Is the stated alcohol-by-volume value identical in both records?',
'Which stock is it being compared against - the second one named, the yardstick?':'Which stock serves as the comparison yardstick, namely the second stock named?',
'Does the state instruct the recipient to subtract the courtesy credit again from total due?':'Is the recipient instructed in the state to deduct the courtesy credit once more from total due?',
'Does the report describe PDF export failing to complete?':'Is a failure to complete PDF export described in the report?',
})
PAIRS.update({
'Which token type does the passage describe as short lived?':'Which type of token is described in the passage as having a short lifetime?',
'How strong are the rights the GDPR grants to individuals over their data?':'To what extent does the GDPR grant individuals rights over their data?',
'Does the `message` ask the recipient to disclose a sensitive credential?':'Is the recipient asked in the `message` to reveal a sensitive credential?',
})
